---

tasks:

  - name: Add hashicorp apt key
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      id: 798AEC654E5C15428C8E42EEAA16FCBCA621E701

  - name: Add hashicorp repository
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main
      state: present
      update_cache: true
